#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.
IP_ADRESS="$1"
if [ -n "$IP_ADRESS" ]; then
    ping -c 5 "$IP_ADRESS"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
